{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    app: {{ default (include "service-chart.fullname" .) .Values.appLabel }}
    {{- with .Values.version }}
    version: {{ . | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ default (include "service-chart.fullname" .) .Values.appLabel }}
      {{- with .Values.version }}
      version: {{ . | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ default (include "service-chart.fullname" .) .Values.appLabel }}
        {{- with .Values.version }}
        version: {{ . | quote }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "service-chart.fullname" . }}
      {{- end }}
      containers:
        - name: {{ include "service-chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: {{ .Values.containerPort }}
            {{- if .Values.healthcheck.enabled }}
            - name: health
              containerPort: {{ .Values.healthcheck.port }}
            {{- end }}
          {{- with .Values.env }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.liveness.path }}
              port: {{ .Values.healthcheck.port }}
            initialDelaySeconds: {{ .Values.healthcheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.readiness.path }}
              port: {{ .Values.healthcheck.port }}
            initialDelaySeconds: {{ .Values.healthcheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.readiness.failureThreshold }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
