{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "service-chart.fullname" .) .Values.service.nameOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ default (include "service-chart.fullname" .) .Values.appLabel }}
    {{- with .Values.service.versionSelector }}
    version: {{ . | quote }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
