{{- range $name, $dep := .Values.dependencies }}
{{- if and $dep.enabled $dep.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: {{ $dep.service.type }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $dep.service.port }}
      targetPort: {{ $dep.service.targetPort }}
{{- end }}
{{- end }}